### ISSUE TITLE
你好怎么和您联系，有问题想请教

### ISSUE THREAD

**Issue by lpy30m** [lanzeweie/xixunyun-b#1]
你好怎么和您联系，有问题想请教

**Comment by lanzeweie** [comment]
github上就可以问

**Comment by lpy30m** [comment]
我挂在青龙上，定时任务执行完后，我应该怎么做才可以推送到pushplush，我是第一次用青龙面板，不太了解，感谢回复

**Comment by lanzeweie** [comment]
在青龙面板Web界面，左侧有个“配置文件”选项 在里面根据你需要推送的机器人填写相关配置即可
