### ISSUE TITLE
我该怎么获取key

### ISSUE THREAD

**Issue by guowang23333** [lanzeweie/xixunyun-b#2]
哥，麻烦说一下key加密公钥咋获取的呗

**Comment by lanzeweie** [comment]
翻阅习讯云网站源码即可获得。
当然找我要也行，不过我需要为此项目得到一些💰

**Comment by lanzeweie** [comment]
翻阅习讯云网站源码即可获得。
当然找我要也行，不过我需要为此项目得到一些💰

**Comment by guowang23333** [comment]
web端就有源码么，还是需要我去逆向app端

**Comment by lanzeweie** [comment]
> web端就有源码么，还是需要我去逆向app端

对 web就有
